### ISSUE TITLE
SQL schema error

### ISSUE THREAD

**Issue by gwillem** [FriendsOfFlarum/username-request#1]
Thanks for making this extension!

However, once FreeFlarum users enable it in the admin panel:

```
[2019-08-14 12:47:45] production.ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null' at line 1 in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61
Stack trace:
#0 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('alter table `us...', Array)
```

Running MariaDB 1:10.1.41-0ubuntu0.18.04.1

Edit: on the forum I read that it would be resolved by upgrading MariaDB. However, I am not keen on backporting MariaDB because a) it may produce other issues and b) I would then be responsible for tracking security issues, which are otherwise handled by the Ubuntu LTS team. So hopefully there is a fix, similar to the fix that was applied to fof/ban-ips?

**Comment by Ralkage** [comment]
@gwillem most certainly! We’ll put it on our to-do and keep you posted :D

**Comment by Ralkage** [comment]
Hi @gwillem, looks as if the JSON datatype is not supported in MariaDB versions below 10.2.7, the JSON datatype support [was added in 10.2.7](https://mariadb.com/kb/en/library/json-data-type/). We would either have to change the logic around a bit which may take some time or just put an indicator in the README that user's may experience issues in older versions of MariaDB.

We could always go the same approach that the user_preferences column logic turns to in the code which is to store the JSON data in a binary blob. Referencing [this migration column](https://github.com/flarum/core/blob/master/migrations/2015_02_24_000000_create_users_table.php#L25) of course :)

I'll discuss with the team and come up with a fix!

**Comment by Ralkage** [comment]
@gwillem and @xCustomWorld this has been fixed 👍

**Comment by xCustomWorld** [comment]
Thank you!

**Comment by gwillem** [comment]
Awesome work!
